name: Build and Test
on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  build-ultraplot:
    name: Test Python ${{ inputs.python-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v2.0.3
        with:
          environment-file: ./environment-dev.yml
          init-shell: bash
          create-args: --verbose
            python=${{ matrix.python-version }}
          cache-environment: true
          cache-downloads: false

      - name: Build Ultraplot
        shell: bash -el {0}
        run: |
          micromamba activate ultraplot-dev
          pip install .

      - name: Generate baseline from main
        shell: bash -el {0}
        run: |
          mkdir -p baseline
          micromamba activate ultraplot-dev
          git fetch origin ${{ github.event.pull_request.base.sha }}
          git checkout ${{ github.event.pull_request.base.sha }}
          pytest --mpl-generate-path=baseline_images
          git checkout ${{ github.sha }}  # Return to PR branch

      - name: Test Ultraplot
        shell: bash -el {0}
        run: |
          micromamba activate ultraplot-dev
          pytest

      # - name: Image Comparison Ultraplot
      #   shell: bash -el {0}
      #   run: |
      #     micromamba activate ultraplot-dev
      #     pytest --mpl --mpl-baseline-path=baseline_images

      # # return the images that failed
      # - name: Upload comparison failures
      #   if: failure()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: failed-comparisons
      #     path: result_images
